language: php

sudo: false

php:
  - 7.4

matrix:
  include:
    - php: 7.4
    - php: 7.4
      env: dependencies=lowest
    allow_failures:
      - php: 8.0
      - php: 8.0
        env: dependencies=lowest

install:
  - composer self-update

before_script:
  - make

script:
  - make qa
  - make test
